<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log in</name>
   <tag></tag>
   <elementGuidId>51f18275-7d4e-4f05-a009-3c34d6ad98d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sol-button.sl-action-btn.sol-button-secondary.sol-button-block.sol-button-m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f049f88-b629-4499-9b90-f3e897f1de35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>655ac3f1-c961-44f3-a174-88732a8bc5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sl-test-data</name>
      <type>Main</type>
      <value>actionButtonsecondary</value>
      <webElementGuid>dbf47107-a438-4d3a-adb0-831c56ece576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sol-button sl-action-btn sol-button-secondary sol-button-block sol-button-m</value>
      <webElementGuid>a644b19b-b6fa-4f36-8e51-740364be28e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dcf9261b-0399-413c-9b8f-bd14437241ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>b2c4a090-a2ea-4cad-8454-2bc2bedd798a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/nav[@class=&quot;sl-navbar dark&quot;]/div[@class=&quot;sl-navbar__container&quot;]/div[@class=&quot;sl-navbar__content active&quot;]/div[@class=&quot;sl-navbar__action-wrapper&quot;]/div[@class=&quot;sl-navigation-actions&quot;]/div[1]/div[@class=&quot;sl-navigation-actions__links-wrapper dark&quot;]/button[@class=&quot;sol-button sl-action-btn sol-button-secondary sol-button-block sol-button-m&quot;]</value>
      <webElementGuid>1a0a40aa-b5cb-4560-a40d-22190cbfc22d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>0c348156-950c-405c-923d-afadf8e3dbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/nav/div/div[3]/div/div/div/div/button</value>
      <webElementGuid>dcf351f6-9f79-4a3f-9146-4fd7719a1af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>a9c53e75-a186-428a-b501-cb4e6254863a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Log in' or . = 'Log in')]</value>
      <webElementGuid>47b63d5e-57a3-4450-a02a-becf47db914e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
