<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign in</name>
   <tag></tag>
   <elementGuidId>dc542b61-c726-4a42-ad38-caf4df46a20c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sol-button.sl-login-login-form__action.sol-button-primary.sol-button-block.sol-button-m</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d6a9481-d502-4700-b7cb-6845fea5046b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>03b11fa9-3b8d-43aa-8779-4c14e5f12615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sl-test-data</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8fe93325-be4c-4e96-acfe-e363e7490f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sol-button sl-login-login-form__action sol-button-primary sol-button-block sol-button-m</value>
      <webElementGuid>9b93cb6d-4cef-4243-ad14-bbc76a8f7c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>556816a6-8e93-46a9-8478-e261ef766b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;sl-user-login&quot;]/div[@class=&quot;sl-user-login__wrapper&quot;]/div[@class=&quot;sl-user-login__content&quot;]/div[@class=&quot;sl-login-container&quot;]/div[@class=&quot;sl-login-login&quot;]/form[@class=&quot;sl-login-login-form&quot;]/button[@class=&quot;sol-button sl-login-login-form__action sol-button-primary sol-button-block sol-button-m&quot;]</value>
      <webElementGuid>50e1e656-af6e-41aa-8b2a-bc8bb901e6b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>42ba0ad5-7e5e-4ed1-8b1c-3f3dc996e7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div/div/form/button</value>
      <webElementGuid>a43bfa4b-32e7-4788-96a0-6100f195391b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c772bb79-719d-474b-a7e1-140f3a7a9216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>1f652b4a-f2fe-4781-a3e9-14b5f55a0a2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
