<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Menu</name>
   <tag></tag>
   <elementGuidId>ee92c357-9793-4400-bfe8-71ad6e6f9ccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sl-hamburger.dark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/nav/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acf3ece1-5a42-4213-bd92-d1e5ca627087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sl-hamburger dark</value>
      <webElementGuid>09eb6045-e2fe-4c7b-8313-970d3dedbee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>459ebf9f-2104-4cba-8fee-3695522759a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/nav[@class=&quot;sl-navbar dark&quot;]/div[@class=&quot;sl-navbar__container&quot;]/div[@class=&quot;sl-hamburger dark&quot;]</value>
      <webElementGuid>404a434b-fb1e-4d6a-8cb8-6fcd6482c2cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/nav/div/div[4]</value>
      <webElementGuid>79fb18bf-5d51-466b-9357-e338adf38b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[4]</value>
      <webElementGuid>f00892d6-a848-40ae-ac40-ecc6acd6dd2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>4b45755b-dcb5-4516-9bb9-7bdef5643f6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
