<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hide</name>
   <tag></tag>
   <elementGuidId>e16dcb2b-fc72-493e-a37f-66033ecff609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sl-p-form-field__password-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div/div/div/div/form/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>baa8d899-c710-453b-8453-b6c57a597661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sl-p-form-field__password-toggle</value>
      <webElementGuid>f307d240-4245-4e29-8a13-b8da0752c722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hide</value>
      <webElementGuid>f1baf43e-cdb8-42f5-962a-6ce4a1ba9be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;sl-user-login&quot;]/div[@class=&quot;sl-user-login__wrapper&quot;]/div[@class=&quot;sl-user-login__content&quot;]/div[@class=&quot;sl-login-container&quot;]/div[@class=&quot;sl-login-login&quot;]/form[@class=&quot;sl-login-login-form&quot;]/div[@class=&quot;sl-p-form-field&quot;]/div[@class=&quot;sl-p-form-field__wrapper&quot;]/span[@class=&quot;sl-p-form-field__password-toggle&quot;]</value>
      <webElementGuid>a5ee2881-12a7-4d0d-a6d9-3744ddeada39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div/div/form/div[2]/div/span</value>
      <webElementGuid>2eb5ef8f-8895-4725-a322-e8f3096b53dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>b5a9fc9f-4007-417c-b7f5-6749118f3198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hide' or . = 'Hide')]</value>
      <webElementGuid>60f1b505-d103-488d-878a-7a35fe4d9766</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
