<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Show</name>
   <tag></tag>
   <elementGuidId>e5e0248f-476d-4234-9b27-4d86a568c4f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sl-p-form-field__password-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div/div/div/div/form/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>842772a8-b311-4e46-98f0-d88bb36277ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sl-p-form-field__password-toggle</value>
      <webElementGuid>493309e7-df08-410f-a378-f71a3057da1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show</value>
      <webElementGuid>1b759930-d910-4baa-9198-5a38e7a22c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;sl-user-login&quot;]/div[@class=&quot;sl-user-login__wrapper&quot;]/div[@class=&quot;sl-user-login__content&quot;]/div[@class=&quot;sl-login-container&quot;]/div[@class=&quot;sl-login-login&quot;]/form[@class=&quot;sl-login-login-form&quot;]/div[@class=&quot;sl-p-form-field&quot;]/div[@class=&quot;sl-p-form-field__wrapper&quot;]/span[@class=&quot;sl-p-form-field__password-toggle&quot;]</value>
      <webElementGuid>4b74c056-5049-4f73-8640-52b89f4ccf7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div/div/div/form/div[2]/div/span</value>
      <webElementGuid>da3d23ca-98ef-432d-82da-5cbf2f12cf48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>57b8dfa1-aa2c-4eba-81dc-f431e947699c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Show' or . = 'Show')]</value>
      <webElementGuid>f210d374-8005-4e4e-849a-a5a9afa1f8e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
