<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_sl-hamburger__button</name>
   <tag></tag>
   <elementGuidId>7bd72650-2aad-48e5-bee4-2fef022a7df9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sl-hamburger__button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/nav/div/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1da169b-57ad-4377-b7af-0e46a6171d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sl-test-data</name>
      <type>Main</type>
      <value>slHamburgerButton</value>
      <webElementGuid>dbcb1199-24b7-4779-8b2b-1842513d034c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sl-hamburger__button</value>
      <webElementGuid>b6ede9cf-5950-4205-87fa-3d942e87d475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/nav[@class=&quot;sl-navbar light&quot;]/div[@class=&quot;sl-navbar__container&quot;]/div[@class=&quot;sl-hamburger light&quot;]/div[@class=&quot;sl-hamburger__button&quot;]</value>
      <webElementGuid>a34b0f94-935c-4cd5-a0f2-93b57265850e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/nav/div/div[4]/div</value>
      <webElementGuid>c5f93e02-fed6-4895-b8c4-021334d68faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[4]/div</value>
      <webElementGuid>569945ee-0623-4be8-bb8c-aa1c5a4fe966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
