<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_current</name>
   <tag></tag>
   <elementGuidId>f9c6985c-f9ee-42dd-a5fe-bc2cdb58b56f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#current</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='current']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60369721-a385-46bc-bfa3-9c63b572de62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sl-p-form-field__input </value>
      <webElementGuid>5e3d5f32-c2de-490b-b134-dca5bed1bcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>33c8731c-92f3-4ce3-adfd-ba3151f86fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>current</value>
      <webElementGuid>38ca5c8e-7e88-491f-8bcc-d16b5d1346e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>current</value>
      <webElementGuid>4d70c088-ce8d-425c-af14-4497e8d3bd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>25c667f9-680d-4698-a8cb-446984069733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;current&quot;)</value>
      <webElementGuid>c1fab721-dd6b-403f-bb42-acef53fdc02e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='current']</value>
      <webElementGuid>a5dbd1a1-c9ae-40d3-9949-99fc2f0e3205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/div/div[2]/div/div[2]/div/div/div/form/div/div/input</value>
      <webElementGuid>20409399-5a4e-4c57-86c7-6e2d906a8e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>f97dfdef-89c3-4fb0-a4cb-c0dd39e1ca9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'current' and @name = 'current']</value>
      <webElementGuid>96142a88-282a-41df-a472-8266b126410d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
