<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sl-p-password-form__submit</name>
   <tag></tag>
   <elementGuidId>b509ebfc-9eab-44ba-b5de-f019849da022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.sl-p-password-form__submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Change']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef1e0027-0b9f-46d4-ad64-21068bd72008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sl-p-password-form__submit</value>
      <webElementGuid>8c319855-9012-4384-b0bf-642482d4ff34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>07aa13c3-b0b9-4405-88f2-0a2700e4d185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>5c2c18b2-bce2-4b4a-8362-0724ea9a4f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[2]/div[1]/div[@class=&quot;sl-profile&quot;]/div[@class=&quot;sl-modal edit-profile&quot;]/div[@class=&quot;sl-modal__container edit-profile&quot;]/div[@class=&quot;sl-modal__content edit-profile&quot;]/div[@class=&quot;sl-p-edit-profile&quot;]/div[@class=&quot;sl-p-edit-profile__body&quot;]/div[@class=&quot;sl-p-password-form&quot;]/form[@class=&quot;sl-p-password-form__form&quot;]/input[@class=&quot;sl-p-password-form__submit&quot;]</value>
      <webElementGuid>e6ff2108-bf26-44b7-a14c-faf408bf7b92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Change']</value>
      <webElementGuid>34532dbd-741d-46cd-a995-e537a42443ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/div/div[2]/div/div[2]/div/div/div/form/input</value>
      <webElementGuid>baee74ca-6802-40a0-84e1-4c243661c079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>08e35e57-cb26-4303-902d-20bdab33db49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>0c32e24a-c325-4335-97d2-03680cde1a83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
