<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_new</name>
   <tag></tag>
   <elementGuidId>26655f1e-3314-4d05-bfb7-6b1e47f3b7f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a60c1a5d-80cd-427c-8364-ffc546a9c2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sl-p-form-field__input </value>
      <webElementGuid>43d32e39-fb66-44ae-a415-4b3697023c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>46741ba2-7ead-4dca-a4ab-c70645a76fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new</value>
      <webElementGuid>5f66cb65-a993-4578-aad8-7c92cde380ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>new</value>
      <webElementGuid>e8b46668-c63e-478e-8c2b-9a5c0854752f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>eaf39025-6d64-49e9-9b38-608fb3f8d537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new&quot;)</value>
      <webElementGuid>eeeb03da-309a-4281-80a1-f48d5bb10e1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='new']</value>
      <webElementGuid>6479908b-51f6-4cca-ad53-b6f70dbc1885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/div/div[2]/div/div[2]/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>027099c1-51d0-40ef-8fdb-61d9fe7cfe35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a468ddb6-b02a-4221-bd3f-6a44eae47c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'new' and @name = 'new']</value>
      <webElementGuid>4e8cdcb2-bc44-437f-bec5-99926c8ecf8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
