<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Statistics</name>
   <tag></tag>
   <elementGuidId>ab202409-875e-4872-ad5e-00eb69aca632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CybotCookiebotDialogBodyLevelButtonsSelectPane']/div[3]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a797cabe-df4d-474d-89c7-92f3df7bc03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyLevelButtonStatistics</value>
      <webElementGuid>c4f94918-6179-40d1-a462-a9c4b4902619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Statistics</value>
      <webElementGuid>437cd8ab-0ee4-4b96-b58b-66b904b37190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CybotCookiebotDialogBodyLevelButtonsSelectPane&quot;)/div[@class=&quot;CybotCookiebotDialogBodyLevelButtonWrapper&quot;]/label[1]</value>
      <webElementGuid>8a3d62ac-ed94-4e04-b0ee-52788b38998d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CybotCookiebotDialogBodyLevelButtonsSelectPane']/div[3]/label</value>
      <webElementGuid>4c3d2ee3-894f-43a4-82e0-3498a34319e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label</value>
      <webElementGuid>11f97639-217b-464b-9a01-08f5c96e1ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Statistics' or . = 'Statistics')]</value>
      <webElementGuid>7d7fa418-9b02-44b2-8896-ab67ed75b9de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
