<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Preferences</name>
   <tag></tag>
   <elementGuidId>60abc0f3-f8c4-4828-96ba-575a59d421f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CybotCookiebotDialogBodyLevelButtonsSelectPane']/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b6c7d9fb-7404-4549-9dd7-04ee415a1a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyLevelButtonPreferences</value>
      <webElementGuid>9fcc3e7a-1dea-46c5-a617-6dbabfd83875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preferences</value>
      <webElementGuid>2f70aff6-16aa-42f2-8e97-9f54b0833f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CybotCookiebotDialogBodyLevelButtonsSelectPane&quot;)/div[@class=&quot;CybotCookiebotDialogBodyLevelButtonWrapper&quot;]/label[1]</value>
      <webElementGuid>d5cd99c1-d999-4bd2-8193-dd54286dae6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CybotCookiebotDialogBodyLevelButtonsSelectPane']/div[2]/label</value>
      <webElementGuid>25278183-2b8b-49b1-b578-607ac80dcce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>6b45fe21-d35c-42f6-946a-c0dc99d6babc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Preferences' or . = 'Preferences')]</value>
      <webElementGuid>a232e0b2-61ab-4ae6-83e8-4ba209dcc43d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
