<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Marketing</name>
   <tag></tag>
   <elementGuidId>bc0f45d4-1e57-4017-97de-9564fb4ea5ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CybotCookiebotDialogBodyLevelButtonsSelectPane']/div[4]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>20e13e4a-9d8c-457d-8474-ec19271ce161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyLevelButtonMarketing</value>
      <webElementGuid>45c0eb86-4157-4e39-90a5-81cc44d658d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marketing</value>
      <webElementGuid>65cf5def-0db0-4fe7-8d42-f12ddd5dc150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CybotCookiebotDialogBodyLevelButtonsSelectPane&quot;)/div[@class=&quot;CybotCookiebotDialogBodyLevelButtonWrapper&quot;]/label[1]</value>
      <webElementGuid>e2ddc840-c307-4e26-8e99-835f3bab336e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CybotCookiebotDialogBodyLevelButtonsSelectPane']/div[4]/label</value>
      <webElementGuid>97cd0bd1-c23c-4904-acba-b30fd4fab845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label</value>
      <webElementGuid>558108a1-b4b9-4faa-a66f-9e6719a535d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Marketing' or . = 'Marketing')]</value>
      <webElementGuid>2af8b6b7-6c28-4467-a1d9-f6532878ae7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
