<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Show</name>
   <tag></tag>
   <elementGuidId>c4b1f5fe-f6d2-4712-a53d-fc96ad08e81f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/div/div/div[2]/div/div[2]/div/div/div/form/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51843059-4e61-469f-80e9-60fc04c69bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sl-p-form-field__password-toggle</value>
      <webElementGuid>99f62d4a-19bb-4748-8567-fec3799c91bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show</value>
      <webElementGuid>ff68b26a-ca50-421e-8881-7b87fe3af1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[2]/div[1]/div[@class=&quot;sl-profile&quot;]/div[@class=&quot;sl-modal edit-profile&quot;]/div[@class=&quot;sl-modal__container edit-profile&quot;]/div[@class=&quot;sl-modal__content edit-profile&quot;]/div[@class=&quot;sl-p-edit-profile&quot;]/div[@class=&quot;sl-p-edit-profile__body&quot;]/div[@class=&quot;sl-p-password-form&quot;]/form[@class=&quot;sl-p-password-form__form&quot;]/div[@class=&quot;sl-p-form-field&quot;]/div[@class=&quot;sl-p-form-field__wrapper&quot;]/span[@class=&quot;sl-p-form-field__password-toggle&quot;]</value>
      <webElementGuid>eb99a35e-670b-462b-b41c-dfa4b71faaf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/div/div[2]/div/div[2]/div/div/div/form/div[2]/div/span</value>
      <webElementGuid>db18d4b2-dd5a-4945-af36-83389ecc3702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/span</value>
      <webElementGuid>84af4ffc-78bc-426f-a55e-54b127e77992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Show' or . = 'Show')]</value>
      <webElementGuid>f7e766a6-9474-4c37-8539-ae20c213ab0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
